
namespace: chubaofs

component:
  master: true
  datanode: true
  metanode: true
  objectnode: true
  client: true
  provisioner: true
  monitor: true
  console: true
  ingress: true

image:
  server: chubaofs/cfs-server:2.4.0
  client: chubaofs/cfs-client:2.4.0
  csi_driver: chubaofs/cfs-csi-driver:2.4.0.110.4
  csi_provisioner: quay.io/k8scsi/csi-provisioner:v1.6.0
  driver_registrar: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
  csi_attacher: quay.io/k8scsi/csi-attacher:v2.0.0
  grafana: grafana/grafana:6.4.4
  prometheus: prom/prometheus:v2.13.1
  consul: consul:1.6.1
  pull_policy: "IfNotPresent"

# store data,log and other data 
path:
  data: /var/lib/chubaofs
  log: /var/log/chubaofs
  monitor: /var/lib/chubaofs_prometheus

master:
  replicas: 4
  cluster: my-cluster
  labels:
    node_selector_key: chubaofs-master
    node_selector_value: enabled
  log_level: error
  retain_logs: 2000
  port: 17010 
  prof: 17020 
  exporter_port: 9500 
  metanode_reserved_mem: "67108864"
  resources:
    enabled: false
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "8000m"

metanode:
  labels:
    node_selector_key: chubaofs-metanode
    node_selector_value: enabled
  log_level: error
  total_mem: "26843545600"
  port: 17210 
  prof: 17220 
  raft_heartbeat: 17230 
  raft_replica: 17240
  exporter_port: 9510 
  resources:
    enabled: true
    requests:
      memory: "32Gi"
      cpu: "2000m"
    limits:
      memory: "256Gi"
      cpu: "8000m"

datanode:
  labels:
    node_selector_key: chubaofs-datanode
    node_selector_value: enabled
  log_level: error
  port: 17310 
  prof: 17320 
  raft_heartbeat: 17330 
  raft_replica: 17340 
  exporter_port: 9520
  disks:
    - /data0:21474836480
    - /data1:21474836480
  resources:
    enabled: false
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "8000m"

objectnode:
  replicas: 3
  log_level: error
  port: 1601 
  prof: 7011
  exporter_port: 9500
  region: "spark"
  domains: "objectcfs.jd.local,objectnode.cfs.jd.local"
  host: objectnode.chubaofs.com
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

client:
  replicas: 1
  vol_name: "test"
  owner: "chubaofs"
  log_level: error
  exporter_port: 9530
  prof: 17410 
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

provisioner:
  dirver_name: csi.chubaofs.com
  log_level: error
  kubelet_path: /var/lib/kubelet

console: 
  replicas: 1
  log_level: error
  port: 1602 
  host: console.chubaofs.com
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

consul:
  port: 8500
  replicas: 1 

grafana:
  port: 3000
  replicas: 1
  host: monitor.chubaofs.com
  admin_password: !!string 123456
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

prometheus:
  port: 9090
  replicas: 1
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

