
namespace: chubaofs

component:
  master: true
  datanode: true
  metanode: true
  objectnode: true
  client: true
  provisioner: false
  monitor: true

image:
  server: chubaofs/cfs-server:2.0.0
  client: chubaofs/cfs-client:2.0.0
  grafana: grafana/grafana:6.4.4
  prometheus: prom/prometheus:v2.13.1
  consul: consul:1.6.1
  pull_policy: "IfNotPresent"

# store data,log and other data 
path:
  data: /var/lib/chubaofs
  log: /var/log/chubaofs
  monitor: /var/lib/chubaofs_prometheus

master:
  replicas: 3
  cluster: my-cluster
  labels:
    node_selector_key: chuabaofs-master
    node_selector_value: enabled
  log_level: info
  retain_logs: 2000
  port: 17010 
  prof: 17020 
  exporter_port: 9500 
  metanode_reserved_mem: "67108864"
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

metanode:
  labels:
    node_selector_key: chuabaofs-metanode
    node_selector_value: enabled
  log_level: info
  total_mem: "17179869184"
  port: 17210 
  prof: 17220 
  raft_heartbeat: 17230 
  raft_replica: 17240
  exporter_port: 9510 
  resources:
    enabled: true
    requests:
      memory: "16Gi"
      cpu: "2000m"
    limits:
      memory: "64Gi"
      cpu: "4000m"

datanode:
  labels:
    node_selector_key: chuabaofs-datanode
    node_selector_value: enabled
  log_level: info
  port: 17310 
  prof: 17320 
  raft_heartbeat: 17330 
  raft_replica: 17340 
  exporter_port: 9520
  disks:
    - /data0:21474836480
    - /data1:21474836480
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

objectnode:
  replicas: 3
  log_level: info
  port: 1601 
  prof: 7011
  exporter_port: 9500
  region: "spark"
  domains: "objectcfs.jd.local,objectnode.cfs.jd.local"
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

client:
  replicas: 1
  vol_name: "test"
  owner: "chubaofs"
  log_level: info
  exporter_port: 9530
  prof: 17410 
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

storageclass:
  provisioner: chubao.io/chubaofs
  name: chubaofs

consul:
  port: 8500
  replicas: 1 

grafana:
  port: 3000
  replicas: 1
  host: monitor.chubaofs.com
  admin_password: !!string 123456
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

prometheus:
  port: 9090
  replicas: 1
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

