{{- if .Values.component.master }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chubaofs-bin
  namespace: {{ .Values.namespace }}
data:
{{- if .Values.component.master }}
  config-master.sh: |+
{{ tuple "bin/_config_master.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  start-master.sh: |+
{{ tuple "bin/_start_master.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.component.datanode }}
  config-datanode.sh: |+
{{ tuple "bin/_config_datanode.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  start-datanode.sh: |+
{{ tuple "bin/_start_datanode.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.component.metanode }}
  config-metanode.sh: |+
{{ tuple "bin/_config_metanode.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  start-metanode.sh: |+
{{ tuple "bin/_start_metanode.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.component.client }}
  config-client.sh: |+
{{ tuple "bin/_config_client.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  check-volumn.sh: |+
{{ tuple "bin/_check_volume.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  start-client.sh: |+
{{ tuple "bin/_start_client.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}
{{- if .Values.component.objectnode }}
  config-objectnode.sh: |+
{{ tuple "bin/_config_objectnode.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
  start-objectnode.sh: |+
{{ tuple "bin/_start_objectnode.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}

{{- end }}

