{{- if .Values.component.ingress }}
{{- $envAll := . }}
{{- $namespace := .Values.namespace }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ $namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
   - host: {{ .Values.grafana.host }}
     http:
       paths:
       - backend:
          serviceName: grafana-service
          servicePort: {{ .Values.grafana.port }}
   - host: {{ .Values.console.host }}
     http:
       paths:
       - backend:
          serviceName: console-service
          servicePort: {{ .Values.console.port }}
   - host: {{ .Values.objectnode.host }}
     http:
       paths:
       - backend:
          serviceName: objectnode-service
          servicePort: {{ .Values.objectnode.port }}
{{ end }}
